# Generated by Django 6.0.3 on 2026-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(db_index=True, default='user', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
