# Generated by Django 6.0.3 on 2026-05-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
